### ISSUE TITLE
Unexpected input 'note'

### ISSUE THREAD

**Issue by v-dimitroff** [SpeedCurve-Metrics/speedcurve-test-action#65]
![Screenshot 2021-08-10 at 11 13 08 AM](https://user-images.githubusercontent.com/85879610/128833194-674bc45a-ae73-4981-9a10-cf94296e8052.png)

I got the above warning when the action is executed. It completes successfully but not surprisingly  the deploy message is again the default one.

If you point me to the place where the issue comes from I will contribute again to fix it.

**Comment by v-dimitroff** [comment]
@josephwynn-sc  I believe the root of the issue is simple because I noticed the deploy hasn't succeeded [github action run](https://github.com/SpeedCurve-Metrics/speedcurve-test-action/actions/runs/1092059691)

I guess this means that the new version is not available which explains why I get the error above.

**Comment by v-dimitroff** [comment]
@josephwynn-sc I am sure you are quite busy and that's why I am posting just a kind reminder on the issue as I feel we are millimetres close to success

**Comment by v-dimitroff** [comment]
@wildlyinaccurate @josephwynn-sc Coming back to the Issue as we are still struggling a lot with differentiate runs on the SpeedCurve dashboards ...

**Comment by josephwynn-sc** [comment]
Sorry @v-dimitroff! I have published v1.2.2 which has your change.

**Comment by v-dimitroff** [comment]
Thank you @josephwynn-sc - appreciate it! Though the issue remains for some reason ... Our latests runs show the same warning output after the workflow has finished.

**Comment by josephwynn-sc** [comment]
@v-dimitroff are you definitely using v1.2.2? I just [tested the note input](https://github.com/SpeedCurve-Metrics/speedcurve-test-action/commit/cdbb6ea28bd8598a83440923e7418478873a8278) and it works:

![Screenshot from 2021-09-20 11-40-59](https://user-images.githubusercontent.com/31634862/133946655-a5f3ac11-5746-4ed4-8834-8d28f06f845d.png)

**Comment by v-dimitroff** [comment]
@josephwynn-sc My bad! You are right, I didn't notice I need to point the version as we were using the v1 major version without other specs. It is working now and to save time for others I will push a PR with the updates and a section for the note param.
